# render.yaml
services:
  - type: web
    name: water-quality-backend
    runtime: python
    pythonVersion: 3.10.12
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
